### PR TITLE
Integration Test

### PR DESCRIPTION
**Pull request by karinamuraya**
-full app test

### CODE REVIEW

**Comment by hanmajid** [comment]
Hi @karinamuraya ! 

Thanks for the pull request 😀. It looks great, but can you please do the following:

1. Delete changes that are not relevant to the integration test (e.g. the `web` folder)
2. Provides an instruction for conducting the integration test.

Thank you!

**Comment by karinamuraya** [comment]
@hanmajid added how to conduct the test, please review

**Review by hanmajid — APPROVED** [review]
Overall, the integration test works well, Karina. I'm going to approve this pull request now, however I'm going to make a few changes too afterwards (for example, changing `?android:colorBackground` in `launch_background.xml` because it knowns for making the app crashes). Otherwise, everything works well! 

Thank you again for your contribution. Feel free to make more pull requests in the future. Have a nice day. 🙂

**Comment by karinamuraya** [comment]
I'm humbled and thank you for your collaboration, I will indeed look to
making more pull requests. Enjoy your day.

**Pull request merged**
